# This dockerfile builds a frontend server image with default name 'cr8s-fe-server'
ARG FE_BASE_IMAGE="junk"
ARG CR8S_VERSION="junk"
FROM ${FE_BASE_IMAGE}
# Install curl for health checks
USER root
RUN echo "Building server version ${CR8S_VERSION}" ; \
    apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

USER dev
