ARG BASE_IMAGE="junk"
ARG CR8S_VERSION="junk"
FROM ${BASE_IMAGE}
LABEL cr8s.base.version=${CR8S_VERSION}
# Install curl for health checks
USER root
RUN echo "Building server version ${CR8S_VERSION}" ; \
    apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
USER appuser
